Feature/player damage state/kmy
KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party pull request #123
Opened 2023-06-19 17:52 UTC by nninyeong

# PR을 하기 전 체크사항
- [x] 임시로 작성한 코드는 모두 제거했나요?
- [x] 주석은 충분히 작성했나요?
- [x] 코드 컨벤션은 지켰나요?
- [x] 폴더구조는 지켰나요?
- [x] 실행했을 때, 오류는 없나요?

# 변경된 기능
1. 플레이어가 데미지를 입었을 때 실행핧 애니메이션 및 파티클 추가
2. 플레이어 Hp 추가
3. 플레이어에게 데미지를 입힐 때 사용할 메소드 추가

# (선택)스크린샷
![Damaged](https://github.com/KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party/assets/74064375/8fd69006-f9bb-45b3-9510-72622545fe8f)

---

# 코드 리뷰 가이드
코드 리뷰를 어떻게 해야하는지 모르겠다면 아래의 사항을 고려해보세요.

- 이름은 충분히 명확한가?
- 코드 흐름은 읽기 쉽게 되어 있는가?
  - 개행은 세부 로직 별로 잘 적용이 되어 있는가?
- 불필요한 객체가 존재하진 않는가?
  - 쓸데없는 Manager 객체가 존재하진 않는가?
- 객체 간 결합도는 충분히 낮은가?
- 불필요한 필드가 존재하진 않는가?
- 다른 객체를 참조할 때, Find()를 사용하고 있진 않은가?
  - Instantiate()를 활용해 참조를 얻어올 수 있진 않은가?
  - 전역적인 접근점을 지닌 다른 객체를 통해서 참조를 얻어올 수 있진 않은가?
- 과도하게 모듈화 되어 있진 않은가?
  - 하나의 함수로 작성할 수 있는 걸 구태여 여러 개로 분리하진 않았는가?
- [주석이 작성되어 있는가?](https://learn.microsoft.com/ko-kr/dotnet/csharp/language-reference/xmldoc/recommended-tags)
  - 모든 public 함수에 주석이 작성되어 있는가?
  - 코드만으로는 이해하기 어려운 부분에 주석이 작성되어 있는가?
- 함수는 하나의 일만 해결하고 있는가?
- Assert()로 사전 조건과 사후 조건을 모두 체크하고 있는가?
  - NullReferenceException이 발생할 만한 부분은 없는가?

2023-06-19 20:14 UTC, rickythediver requested changes

2023-06-19 20:14 UTC, rickythediver commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Player/DamagedBehaviour.cs
> +            elapsedTime += Time.deltaTime;
elapsedTime += Time.deltaTime을 여기서 해버리면 0부터 시작하지 않게 되어버립니다 ㅠ

2023-06-19 20:14 UTC, rickythediver commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Player/DamagedBehaviour.cs
> +    public override void OnStateUpdate(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
이거 혹시 start에서 유니태스크로 바꿔줄 수 있나요?? 근데 생각해보니 그냥 애니메이션을 하나 만드는게 훨씬 편할거 같다는 생각이 들었음

2023-06-19 20:14 UTC, rickythediver commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Player/DamagedBehaviour.cs
> +    public override void OnStateUpdate(Animator animator, AnimatorStateInfo stateInfo, int layerIndex)
4바퀴 도는 애니메이션

2023-06-19 20:14 UTC, rickythediver commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Player/DamagedBehaviour.cs
> +            lerpRot.y %= MAX_ROTATE_DEGREE;
이 부분이 문제인거 같은데, 플레이어가 4바퀴를 돌고 정면을 보는게 아닌 다른 대각선 방향을 바라보네요

2023-06-20 06:38 UTC, eunning09005 approved these changes

2023-06-20 07:34 UTC, 0105kcy approved these changes

2023-06-20 07:50 UTC, rickythediver approved these changes
졸귀

2023-06-20 07:50 UTC, merged