Feature/mini game info/kcy
KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party pull request #170
Opened 2023-07-02 23:12 UTC by 0105kcy

# PR을 하기 전 체크사항
PR 전에 아래의 내용을 수행했는지 하나씩 체크해봅시다.

- [X] 임시로 작성한 코드는 모두 제거했나요?
- [X] 주석은 충분히 작성했나요?
- [X] 코드 컨벤션은 지켰나요?
- [X] 폴더구조는 지켰나요?
- [X] 실행했을 때, 오류는 없나요?

# 변경된 기능
달라진 기능에는 무엇이 있는지 목록으로 작성합니다.

- 목록 1 보드게임 씬에 미니게임의 정보를 알릴 캔버스 추가
- 목록 2 캔버스에 타이머를 추가하고 타이머 종료 시 씬 전환 부분 만듬(현재는 비활성화)
- 목록 3 룸의 커스텀 프로퍼티로 미니게임을 매핑한 인덱스 넣음
- 목록 4 룸의 커스텀 프로퍼티에 맥스 턴, 턴 타임 추가
- 목록 5 프로퍼티키 추가
- 목록 6 CSV 파서 추가
- 목록 7 미니게임 정보를 담은 CSV문서 추가(씬넘버를 가지고 있음)
- 목록 8 알파벳과 숫자 스프라이트 추가(써먹을 곳이 있을듯?) 텍스트로 처리하지 않고 이미지로 처리함

# (선택)스크린샷
이 기능과 관련된 스크린샷을 추가합니다. (동영상 가능)

https://github.com/KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party/assets/120005245/3e340da8-49b4-4ee0-8960-701d070921bd

---

# 코드 리뷰 가이드
코드 리뷰를 어떻게 해야하는지 모르겠다면 아래의 사항을 고려해보세요.

- 이름은 충분히 명확한가?
- 코드 흐름은 읽기 쉽게 되어 있는가?
  - 개행은 세부 로직 별로 잘 적용이 되어 있는가?
- 불필요한 객체가 존재하진 않는가?
  - 쓸데없는 Manager 객체가 존재하진 않는가?
- 객체 간 결합도는 충분히 낮은가?
- 불필요한 필드가 존재하진 않는가?
- 다른 객체를 참조할 때, Find()를 사용하고 있진 않은가?
  - Instantiate()를 활용해 참조를 얻어올 수 있진 않은가?
  - 전역적인 접근점을 지닌 다른 객체를 통해서 참조를 얻어올 수 있진 않은가?
- 과도하게 모듈화 되어 있진 않은가?
  - 하나의 함수로 작성할 수 있는 걸 구태여 여러 개로 분리하진 않았는가?
- [주석이 작성되어 있는가?](https://learn.microsoft.com/ko-kr/dotnet/csharp/language-reference/xmldoc/recommended-tags)
  - 모든 public 함수에 주석이 작성되어 있는가?
  - 코드만으로는 이해하기 어려운 부분에 주석이 작성되어 있는가?
- 함수는 하나의 일만 해결하고 있는가?
- Assert()로 사전 조건과 사후 조건을 모두 체크하고 있는가?
  - NullReferenceException이 발생할 만한 부분은 없는가?

2023-07-03 03:08 UTC, rickythediver requested changes
전체적으로 설명 한번 들어야할 것 같습니다

2023-07-03 03:08 UTC, rickythediver commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Turn/UIPresenter.cs
> +    public UnityEvent Info;
이벤트라서 On 어쩌구저쩌구 이런식으로 네이밍컨벤션 수정해주세요

2023-07-03 03:08 UTC, rickythediver commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/UI/MinigameInformation.cs
> +        presenter.Info.Invoke();
?.Invoke()로 수정해주세요(없으면 실행안되게끔)

2023-07-04 00:15 UTC, 0105kcy commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Turn/UIPresenter.cs
> +    public UnityEvent Info;
수정

2023-07-04 00:15 UTC, 0105kcy commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/UI/MinigameInformation.cs
> +        presenter.Info.Invoke();
수정

2023-07-05 05:38 UTC, rickythediver commented
어차피 바꿀꺼라 걍 닫

2023-07-05 05:38 UTC, closed without merging