#193 DataManager 구현
KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party pull request #194
Opened 2023-07-10 08:01 UTC by rickythediver

# PR을 하기 전 체크사항
PR 전에 아래의 내용을 수행했는지 하나씩 체크해봅시다.

- [x] 임시로 작성한 코드는 모두 제거했나요?
- [x] 주석은 충분히 작성했나요?
- [x] 코드 컨벤션은 지켰나요?
- [x] 폴더구조는 지켰나요?
- [x] 실행했을 때, 오류는 없나요?

# 변경된 기능
달라진 기능에는 무엇이 있는지 목록으로 작성합니다.

- 목록 1 : DataManager 를 구현하였습니다
- 목록 2 : CsvHelper 를 도입하였습니다
- 목록 3 : 데이터테이블을 수정하였습니다

# 제안 사항
위의 기능을 달성하기 위해 프로젝트에 어떤 변화를 주었는지 작성합니다.

- 목록 1
> 이유 : 데이터를 수월하게 관리하기 위함
- 목록 2
> 이유 : CSVHelper를 이용하여 수월한 파싱을 구현

# (선택)스크린샷
![image](https://github.com/KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party/assets/120005134/0afece2f-d4a1-4658-af50-b7f410694b9a)
![image](https://github.com/KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party/assets/120005134/58319af5-e96f-42bb-94a8-a02aee2e5693)

---

# 코드 리뷰 가이드
코드 리뷰를 어떻게 해야하는지 모르겠다면 아래의 사항을 고려해보세요.

- 이름은 충분히 명확한가?
- 코드 흐름은 읽기 쉽게 되어 있는가?
  - 개행은 세부 로직 별로 잘 적용이 되어 있는가?
- 불필요한 객체가 존재하진 않는가?
  - 쓸데없는 Manager 객체가 존재하진 않는가?
- 객체 간 결합도는 충분히 낮은가?
- 불필요한 필드가 존재하진 않는가?
- 다른 객체를 참조할 때, Find()를 사용하고 있진 않은가?
  - Instantiate()를 활용해 참조를 얻어올 수 있진 않은가?
  - 전역적인 접근점을 지닌 다른 객체를 통해서 참조를 얻어올 수 있진 않은가?
- 과도하게 모듈화 되어 있진 않은가?
  - 하나의 함수로 작성할 수 있는 걸 구태여 여러 개로 분리하진 않았는가?
- [주석이 작성되어 있는가?](https://learn.microsoft.com/ko-kr/dotnet/csharp/language-reference/xmldoc/recommended-tags)
  - 모든 public 함수에 주석이 작성되어 있는가?
  - 코드만으로는 이해하기 어려운 부분에 주석이 작성되어 있는가?
- 함수는 하나의 일만 해결하고 있는가?
- Assert()로 사전 조건과 사후 조건을 모두 체크하고 있는가?
  - NullReferenceException이 발생할 만한 부분은 없는가?

2023-07-10 08:41 UTC, ChoiSeonMun requested changes

2023-07-10 08:41 UTC, ChoiSeonMun commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/Managers/DataManager.cs
> +    private const string csvPath = "Assets/Resources/CSVs/";
```suggestion
    private const string csvPath = Path.Combine("Assets", "Resources", "CSVs");
```

2023-07-10 08:41 UTC, ChoiSeonMun commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/Managers/DataManager.cs
> +        Items = ParseToDict<int, ItemData>($"{csvPath}ItemTable.csv", data => data.ID);
```suggestion
        Items = ParseToDict<int, ItemData>(Path.Combine(csvPath, "ItemTable.csv"), data => data.ID);
```

2023-07-10 08:41 UTC, ChoiSeonMun commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/Managers/DataManager.cs
> +    public Dictionary<Player, PlayerData> Players { get; private set; } = new Dictionary<Player, PlayerData>();
Photon쪽에서 관리하는 게 맞음.

2023-07-10 08:41 UTC, ChoiSeonMun commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/Managers/DataManager.cs
> +    public Dictionary<int, AwardData> Awards { get; private set; }
식별자가 모두 1부터 시작하는데 Dict보다는 List지.

2023-07-11 02:45 UTC, rickythediver commented
작은 커밋 위해 close

2023-07-11 02:45 UTC, closed without merging