[Feature] 플레이어, 주사위 연결
KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party pull request #99
Opened 2023-06-15 13:48 UTC by eunning09005

# 변경된 기능
- 주사위 Roll 종료 시 플레이어 이동하는 함수 호출하도록 이벤트 생성 및 구독
- 플레이어 이동 종료시 다시 주사위 활성화 함수 호출

2023-06-15 16:05 UTC, 0105kcy approved these changes

2023-06-15 17:00 UTC, rickythediver requested changes

2023-06-15 17:02 UTC, rickythediver commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Dice/Dice.cs
그리고 지금 PR에 Assignee, Labels, Projects 를 포함해서 아무것도 안달려있음

2023-06-16 22:36 UTC, eunning09005 commented
![Team_Immortal_Sprouts_Pummel_Party_-_BoardGame_NESS_-_Android_-_Unity_2021_3_21f1_Personal__DX11__2023-06-17_07-23-44_AdobeExpress](https://github.com/KIA-PROGRAMMING-38/Team_Immortal-Sprouts_Pummel-Party/assets/120005294/f1dd6e78-d168-43e8-b4b5-77119b81a922)

2023-06-16 22:38 UTC, eunning09005 commented on Team_Immortal Sprouts_Pummel Party/Assets/Scripts/2_Boardgame Scene/Dice/Dice.cs
로직을 바꿔서 폴링이 아닌 비동기로 구현 수정했습니다
라벨 및 프로젝트도 할당했습니다

2023-06-17 10:24 UTC, rickythediver approved these changes

2023-06-17 10:25 UTC, merged